
title: Portfolio
description: Project Portfolio and maybe other things

collections:
  projects:
    output: true
    permalink: /projects/:name/

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    css_class: 'highlight'