
title: Portfolio
description: Project Portfolio and maybe other things

collections:
  projects:
    output: true
    permalink: /projects/:name/
  games:
    output: true
    permalink: /games/:name/

markdown: kramdown