
title: Portfolio
description: Portfolio for my projects and other miscellaneous things.

collections:
  projects:
    output: true
    permalink: /projects/:name/
  games:
    output: true
    permalink: /games/:name/

markdown: kramdown